export { HotelsForm } from './ui/HotelsForm/HotelsForm'
export { HotelsList } from './ui/HotelsList/HotelsList'
export { FavoritesList } from './ui/FavoritesList/FavoritesList'
export { hotelsReducer, hotelsActions } from './model/slice/hotelsSlice'
export type { HotelsType } from './model/types/HotelsType'
